apiVersion: v1
kind: Pod
metadata:
  namespace: circleci
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: app-container
    image: quay.io/ralvares/myapp:latest
    ports:
    - containerPort: 8080
    securityContext:
      privileged: true
