apiVersion: v1
kind: Pod
metadata:
  name: prod-app
  labels:
    app: prod-app
spec:
  containers:
  - name: app-container
    image: quay.io/ralvares/ubi8:minimal
    ports:
    - containerPort: 8080
    securityContext:
      privileged: true
